name: Build Rosettier for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Clean Previous Builds
      run: |
        rm -rf build dist app.spec

    - name: Build Executable
      run: |
        pyinstaller --onefile \
                   --add-data "assets/logo.png:assets" \
                   --noconsole \
                   --icon=assets/Rosetter.ico \
                   --hidden-import importlib_metadata \
                   --hidden-import streamlit.app \
                   --hidden-import streamlit.web \
                   --hidden-import streamlit.runtime.scriptrunner \
                   --copy-metadata streamlit \
                   app.py

    - name: Upload Linux Executable
      uses: actions/upload-artifact@v3
      with:
        name: Rosettier-Linux
        path: dist/app
